dist: trusty
language: rust
rust:
  - stable
  - nightly

script:
  - cargo build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo test --features capture
    fi
